package seeds

import (
	"flonn-be/pkg/entity"

	"gorm.io/gorm"
)

func (s *seeder) seedBiodiversity(sql *gorm.DB) error {
	var objects []entity.Biodiversity

	if err := sql.First(&objects).Error; err != gorm.ErrRecordNotFound {
		return err
	}
	objects = []entity.Biodiversity{
		{
			Name:            "Harimau Sumatera",
			LatinName:       "Panthera tigris sumatrae",
			Populasi:        "400 - 500 Ekor",
			BeratBadan:      "110 - 140",
			UkuranTubuh:     "2.1 - 2.3",
			RentangUsia:     "15 - 26",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FHarimauBanner.png?alt=media&token=34ce0be2-b985-457e-ae58-bcc88b337c5b",
			Description:     "Harimau Sumatera, yang dikenal dengan nama ilmiah Panthera tigris sumatrae, adalah harimau khas yang cuma bisa ditemukan di Pulau Sumatera, Indonesia. Harimau ini ukurannya lebih kecil dibandingkan kerabatnya yang lain, tapi jangan salah, mereka tetap ganas dan kuat lho Sobat Flonn. Dengan corak belang-belang hitam yang mencolok di atas bulu oranye yang terang, mereka jadi juara dalam bersembunyi dan mendadak muncul untuk mengejutkan mangsa.<>Si raja hutan ini memiliki kemampuan yang luar biasa dalam berburu. Mereka bisa melompat jauh dan berenang dengan baik, hal yang nggak semua kucing besar bisa lakukan. Keahlian ini penting banget untuk bertahan hidup di hutan Sumatera yang lembap dan seringkali banjir.<>Harimau Sumatera juga penting banget untuk ekosistem di sekitarnya. Mereka membantu menjaga keseimbangan populasi hewan lain, karena sebagai predator puncak, mereka berburu hewan yang sakit atau lemah. Ini berarti hutan tetap sehat dan semua yang tinggal di sana bisa dapet makanan cukup.			<>Sayangnya, Harimau Sumatera sekarang ini terancam punah karena hutan mereka terus berkurang akibat pembalakan dan konversi lahan menjadi perkebunan. Ditambah lagi dengan perburuan ilegal, jumlah mereka di alam liar kian hari kian sedikit. Upaya konservasi sedang dikebut, dengan harapan kita masih bisa melihat mereka berkeliaran bebas di habitat aslinya.",
			Characteristics: "Lincah dan Kuat:Harimau Sumatera adalah pemangsa yang cekatan dan gesit, seperti atlet elit di dunia satwa.<>Ukuran Lebih Kecil:Dibandingkan spesies harimau lainnya, mereka memiliki ukuran lebih kecil, tapi tetap menjadi predator yang ditakuti.<>Bulu Oranye dan Belang Hitam:Berpenampilan mencolok dengan bulu oranye menyala dan belang hitam yang khas, meski lebih suka bersembunyi di balik gelapnya hutan.<>Ahli Beradaptasi:Mampu hidup di berbagai kondisi, dari hutan lebat hingga di dekat sungai, mereka beradaptasi untuk terus menjadi penguasa wilayahnya.<>Peran Vital dalam Ekosistem:Mereka mengendalikan populasi hewan mangsa, menjaga keseimbangan alam, dan mencegah overpopulasi yang bisa merusak ekosistem.<>Soliter namun Peduli Keluarga:Walaupun cenderung hidup sendirian, harimau Sumatera sangat peduli terhadap anak-anaknya, mengajarkan mereka cara berburu dan bertahan hidup hingga mandiri.",
			Status:          "Kritis (Critically Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Kerusakan Habitat akibat pembukaan lahan untuk perkebunan kelapa sawit dan industri kertas.:Perburuan ilegal bagian tubuh harimau yang bernilai tinggi di pasar gelap.:Konflik dengan manusia dikarenakan hilangnya habitat.:Masih ada kepercayaan bahwa bagian tubuh harimau memiliki khasiat medis.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FHarimauChar.png?alt=media&token=9b422a0a-1851-48d4-91fa-d4494280f8e7",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FHarimau1.png?alt=media&token=f9ee879b-96c5-43dc-88df-6ebbae6ac08b<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FHarimau2.png?alt=media&token=b92537df-c0d0-432d-8841-39b94ffd65a8<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FHarimau3.png?alt=media&token=18dd293c-2ab6-4988-8777-1b0b680f4c87<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FHarimau4.png?alt=media&token=71df7492-4faa-40a7-b49e-d05ed20bd1d0",
			Latitude:        -0.9492,
			Longitude:       100.3543,
			StatusID:        5,
			HabitatID:       7,
			SpeciesID:       1,
		},
		{
			Name:            "Burung Cenderawasih",
			LatinName:       "Cicinnurus regius",
			Populasi:        "100 - 200 Ekor",
			BeratBadan:      "50 - 190",
			UkuranTubuh:     "0.16 - 0.35",
			RentangUsia:     "5 - 8",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FCenderawasihBanner.png?alt=media&token=092e8ef5-097a-4339-b2cd-adcf3d5e59ec",
			Description:     "Pernah mendengar tentang si 'fashionista' alam yang selalu tampil memukau di catwalk hutan Papua? Itulah si Raja Ampat cendrawasih, burung yang tidak hanya mencuri perhatian dengan tarian-tarian kawinnya yang spektakuler, tetapi juga dengan ensemble bulu-bulunya yang secerah warna-warni kanvas pelukis. Sobat Flonn, ini bukan sekadar burung. Ini adalah ekspresi alam yang berjalan-jalan, memperagakan bulu eksotisnya seperti perhiasan mahkota, dan setiap helai bulunya berkilauan di bawah sorotan matahari tropis. Tarian mereka? Yah, bayangkan Broadway di hutan—setiap langkah kaki dan hentakan sayap adalah pertunjukan yang dirancang untuk menghipnotis siapapun yang beruntung menyaksikannya.<>Habitat mereka di kanopi hutan adalah panggung VIP mereka, tempat mereka merajut sarang cinta dan menunaikan serenade matahari terbit. Keberagaman menu mereka yang istimewa, dari buah-buahan manis hingga ke serangga yang renyah, adalah bukti dari adaptasi mereka yang luar biasa dalam mengeruk segala nikmat yang ditawarkan oleh hutan mereka yang penuh misteri.<>Namun, tak semua yang berkilau itu emas, sobat Flonn. Dunia mereka yang menakjubkan ini menghadapi badai yang disebabkan oleh tangan-tangan manusia yang tak kenal belas kasihan. Hutan yang pernah berdendang kini menghadapi simfoni gergaji mesin dan lahan yang berkurang, sementara ancaman dari perdagangan ilegal mengintai dari bayang-bayang, mempertaruhkan masa depan dari pertunjukan alam ini.",
			Characteristics: "Bulu Berwarna-Warni:Para jantan memiliki bulu mencolok yang berwarna seperti pelangi, dengan kombinasi kuning emas, merah menyala, dan biru laut.<>Pameran Keindahan Saat Musim Kawin:Jantan merentangkan bulu-bulu mereka seperti kipas raksasa untuk menarik perhatian betina saat musim kawin.<>Tarian Kawin yang Rumit:Selain bulu yang indah, jantan melakukan tarian kawin yang rumit, lengkap dengan gerakan khas dan suara unik, seolah sedang melakukan drama.<>Persiapan Panggung Tarian:Jantan membersihkan area dari daun dan ranting untuk dijadikan “panggung” dalam pertunjukan tarian mereka demi memikat pasangan.<>Hidup di Ketinggian:Mereka memilih pohon-pohon yang tinggi dan lebat sebagai tempat tinggal dan berkembang biak, menciptakan benteng alami dari ancaman.",
			Status:          "Kritis (Critically Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Deforestasi di Papua mengancam habitat alami burung cendrawasih.:Perubahan pola cuaca akibat perubahan iklim memengaruhi ketersediaan makanan dan kondisi hidup mereka.:Burung cendrawasih dan bulunya masih menjadi target perdagangan ilegal.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FCenderawasihChar.png?alt=media&token=083afade-a754-4342-b362-7a77cda4925f",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FCenderawasih1.png?alt=media&token=7e4b8346-95c5-4ebb-9fdc-2cf7d8e8a34f<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FCenderawasih2.png?alt=media&token=59d78376-ccb5-4bb5-984e-612763bc75a9<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FCenderawasih3.png?alt=media&token=c2d6ff5f-bf9d-4e52-8433-49703b23c849<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FCenderawasih4.png?alt=media&token=4615dadb-b446-45df-a92b-a205a570c357",
			Latitude:        -3.6,
			Longitude:       135.5,
			StatusID:        5,
			HabitatID:       7,
			SpeciesID:       1,
		},
		{
			Name:            "Orangutan Kalimantan",
			LatinName:       "Pongo pygmaeus",
			Populasi:        "1000 - 1100 Ekor",
			BeratBadan:      "30 - 90",
			UkuranTubuh:     "1.25 - 1.5",
			RentangUsia:     "35 - 50",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FOrangutanBanner.png?alt=media&token=804c24b7-758b-43bd-a546-7caf02f0a206",
			Description:     "Orangutan Kalimantan, makhluk cerdas yang hanya bisa ditemukan di hutan tropis Kalimantan, adalah bagian dari keluarga besar primata. Mereka memiliki ciri khas berupa bulu panjang berwarna merah kecoklatan dan wajah yang ekspresif, yang membuat mereka salah satu hewan paling ikonik di Indonesia. Dengan lengan yang panjang dan kuat, Orangutan Kalimantan mahir dalam memanjat dan bergelantungan di pohon-pohon tinggi, menjadikan kanopi hutan sebagai rumah mereka yang nyaman.<>Dalam kehidupan sosialnya, Orangutan Kalimantan cenderung bersifat soliter, terutama para jantan dewasa. Mereka memiliki wilayah kekuasaan yang luas dan biasanya hanya bertemu dengan orangutan lain untuk berkembang biak atau secara kebetulan di tempat makanan melimpah. Namun, orangutan betina dan anak-anaknya memiliki ikatan yang kuat. Orangutan betina sangat perhatian dalam merawat anak-anaknya, yang bergantung pada ibu mereka untuk makan dan belajar bertahan hidup selama beberapa tahun.<>Sayangnya, meskipun begitu mengagumkan, keberadaan Orangutan Kalimantan terancam oleh berbagai faktor, terutama kehilangan habitat akibat deforestasi. Hutan-hutan di Kalimantan terus berkurang karena diubah menjadi lahan pertanian dan perkebunan, membuat orangutan ini kehilangan rumahnya. Selain itu, perdagangan ilegal dan konflik dengan manusia juga menjadi ancaman serius yang dihadapi oleh spesies ini. Usaha konservasi terus dilakukan untuk memastikan bahwa generasi mendatang masih dapat menyaksikan keberadaan Orangutan Kalimantan di alam liar.",
			Characteristics: "Ciri Fisik:Memiliki wajah lebih datar dan bulu yang lebih gelap dibandingkan orangutan Sumatra.<>Ahli Memanjat:Sebagian besar waktu dihabiskan di pohon-pohon besar, dengan lengan panjang dan kuat yang membantu mereka memanjat serta berayun dari pohon ke pohon.<>Kecerdasan Tinggi:Dikenal karena kemampuan menggunakan alat sederhana, seperti ranting untuk menggali serangga, daun sebagai pelindung dari hujan, atau sarung tangan untuk memegang buah berduri.<>Perilaku Sosial:Selain untuk bertahan hidup, kecerdasan mereka juga terlihat dalam interaksi sosial yang kompleks.<>Reproduksi:Betina melahirkan setiap delapan tahun sekali, interval kelahiran terpanjang di antara mamalia.",
			Status:          "Terancam Punah (Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Deforestasi untuk lahan pertanian, perkebunan, dan pertambangan telah mengurangi habitat alami orang utan.:Seringkali konflik dengan manusia dikarenakan memasuki lahan untuk mencari makan.:Bayi orangutan sering ditangkap untuk dijual sebagai hewan peliharaan ilegal, melibatkan pembunuhan terhadap ibu orangutan.:Dengan interval kelahiran yang sangat panjang, perburuan terhadap induk orangutan berdampak besar pada regenerasi populasi.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FOrangUtanChar.png?alt=media&token=6ccb7999-f048-4aa0-b1ff-27613f5d8c8b",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FOrangutan1.png?alt=media&token=a6538942-ca1c-439e-93d5-bedb696be697<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FOrangutan2.png?alt=media&token=022ad1eb-1089-4c22-9cae-e26f2523aad9<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FOrangutan3.png?alt=media&token=fdded022-01f7-45e9-a38a-715eeff42cd8<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FOrangutan4.png?alt=media&token=51965c0e-ab8c-46c3-856b-b2793a617e35",
			Latitude:        -2.2083,
			Longitude:       113.9108,
			StatusID:        4,
			HabitatID:       7,
			SpeciesID:       1,
		},
		{
			Name:            "Penyu Hijau",
			LatinName:       "Chelonia mydas",
			Populasi:        "15000 - 20000 Ekor",
			BeratBadan:      "130 - 190",
			UkuranTubuh:     "0.83 - 0.9",
			RentangUsia:     "20 - 50",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FPenyuhijauBanner.png?alt=media&token=ee9144d9-3f5b-4c8d-9b8b-071368c36a38",
			Description:     "Penyu hijau, yang memiliki nama ilmiah Chelonia mydas, merupakan salah satu spesies penyu yang paling dikenal di dunia. Mereka mendapatkan nama mereka dari warna kehijauan lemak di bawah kulit mereka. Penyu ini dapat tumbuh hingga mencapai panjang sekitar 1,5 meter dan beratnya bisa mencapai lebih dari 300 kg. Dengan bentuk tubuh yang besar dan berat, penyu hijau memiliki ciri khas dengan cangkangnya yang berbentuk seperti hati dan berwarna coklat kehijauan.<>Habitat utama penyu hijau terletak di perairan tropis dan subtropis di seluruh dunia, termasuk di perairan Indonesia yang kaya akan terumbu karang. Mereka adalah hewan yang menyukai kedalaman, sering ditemukan di lagoon dangkal dan di pantai berpasir di mana mereka bertelur. Siklus hidup penyu hijau sangat menarik, di mana mereka akan kembali ke pantai dimana mereka lahir untuk bertelur setelah berkelana di lautan.<>Penyu hijau menghadapi banyak ancaman yang berpotensi menyebabkan kepunahan. Ancaman ini termasuk perburuan liar, kehilangan habitat bertelur karena pembangunan pesisir, polusi laut, serta tertangkapnya mereka secara tidak sengaja dalam alat tangkap ikan. Upaya konservasi global sedang dijalankan untuk melindungi spesies ini, termasuk perlindungan area bertelur dan regulasi ketat terhadap penangkapan di laut. Kita semua bisa berkontribusi dengan mendukung upaya konservasi dan menjadi lebih sadar akan dampak aktivitas manusia terhadap kehidupan laut.",
			Characteristics: "Warna Tubuh:Warna tubuh penyu hijau lebih ke arah coklat zaitun dengan pola bercak-bercak di karapas (tempurung).<>Herbivora:Berbeda dari kebanyakan penyu lainnya, penyu hijau dewasa memakan rumput laut dan alga.<>Migrasi Jauh:Mereka dikenal sebagai perenang jarak jauh yang dapat bermigrasi ribuan kilometer antara tempat makan dan lokasi bertelur.<>Proses Bertelur:Betina akan kembali ke pantai tempat mereka menetas untuk bertelur, biasanya menggali sarang di pasir pantai untuk menyimpan telur-telurnya.<>Usia Panjang:Penyu hijau bisa hidup hingga 80 tahun atau lebih, menjadikannya salah satu hewan dengan umur panjang di laut.",
			Status:          "Terancam Punah (Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Penyu hijau diburu untuk daging, telur, dan cangkangnya, yang memiliki nilai tinggi di pasar gelap.:Pembangunan dan pariwisata menghancurkan pantai-pantai tempat mereka bertelur.:Penyu sering salah mengira plastik sebagai ubur-ubur, menyebabkan penyumbatan internal yang fatal.:Perubahan suhu pasir di lokasi bertelur akibat perubahan iklim memengaruhi rasio kelamin anak penyu.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FPenyuChar.png?alt=media&token=8d3b4381-a1da-4239-ae57-927af2e4e0be",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FPenyuHijau1.png?alt=media&token=16fa2b13-2644-4c79-9578-25cf75f0bb9f<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FPenyuHijau2.png?alt=media&token=00d449f1-eba3-4d20-b0b2-35c31e0b3240<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FPenyuHijau3.png?alt=media&token=9d454396-fa39-4f59-925f-2c6cc547c763<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FPenyuHijau4.png?alt=media&token=8746a98b-9d53-4ebc-b6b5-ee9c833166d5",
			Latitude:        -9.00,
			Longitude:       110,
			StatusID:        3,
			HabitatID:       8,
			SpeciesID:       1,
		},
		{
			Name:            "Merak Hijau",
			LatinName:       "Pavo muticus",
			Populasi:        "800 - 900 Ekor",
			BeratBadan:      "4 - 5",
			UkuranTubuh:     "2 - 3",
			RentangUsia:     "20 - 27",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FMerakHijauBanner.png?alt=media&token=05eb712a-ff1e-4d7d-91ca-13a922c3d3dd",
			Description:     "Halo sobat Flonn! Mari kita ulik lebih dalam tentang Merak Hijau, atau yang dikenal dengan nama ilmiahnya Pavo muticus. Burung ini merupakan salah satu makhluk terindah dengan bulu dominan berwarna hijau zamrud dan biru cerah yang pastinya akan membuat siapa saja terpesona. Berbeda dengan Merak India yang mungkin lebih familiar bagi kita, Merak Hijau memiliki ciri khas bulu ekor yang lebih ramping dan kurang lebar, tetapi tetap spektakuler ketika ia mengembangkannya dalam tarian kawin yang sangat elegan.<>Untuk sobat Flonn yang mungkin belum tahu, Merak Hijau ini adalah jenis burung yang cukup pemalu dan lebih sulit untuk ditemukan dibandingkan dengan Merak India. Meskipun mereka bisa terbang, lebih sering kita akan menemukan Merak Hijau berjalan-jalan di tanah daripada terbang. Mereka juga memiliki suara yang khas yang sering digunakan untuk berkomunikasi antar sesama, terutama pada masa kawin atau ketika merasa terancam.<>Sayangnya, keberadaan Merak Hijau saat ini terancam punah, dengan perusakan habitat dan perburuan menjadi dua faktor utama. Berbagai upaya konservasi sedang dilakukan untuk menjaga kelangsungan hidup mereka, termasuk perlindungan habitat dan program pembiakan. Keindahan alami dan keunikan perilaku Merak Hijau membuatnya menjadi simbol penting dari kekayaan alam yang harus kita jaga demi kelangsungan kehidupan berbagai spesies di bumi.",
			Characteristics: `Warna Cemerlang:Bulu dominan berwarna hijau zamrud dengan kilauan biru saat terkena sinar matahari.<>Mahkota Bulu:Memiliki mahkota kecil di kepala yang terdiri dari bulu halus.<>Ekor Panjang:Bulu ekor panjang berwarna hijau, berbeda dengan Merak India yang memiliki ekor lebih cerah dan lebar.<>Perilaku Pendiam dan Pemalu:Merak hijau cenderung lebih pemalu dan pendiam, lebih suka bersembunyi di bawah kanopi hutan.<>Teritorial Saat Musim Kawin:Jantan menjadi sangat teritorial dan menampilkan ekornya yang panjang dan mengagumkan untuk menarik perhatian betina.<>Kaki Kuat:Kaki mereka yang kuat memudahkan mereka berjalan di lantai hutan yang lembap dan tidak rata, serta membantu menggali tanah untuk mencari makanan.`,
			Status:          "Terancam Punah (Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Deforestasi dan konversi hutan menjadi lahan pertanian atau pemukiman mengakibatkan hilangnya habitat.:Diburu untuk peliharaan dan bulu, meski dilarang CITES.:Hilangnya vegetasi memaksa merak mencari makan lebih jauh.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FMerakChar.png?alt=media&token=1fb21f74-493d-47a2-8112-5cc2c3061810",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FMerak1.png?alt=media&token=9e622a0b-f310-4cec-8b57-9cd67a4961c2<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FMerak2.png?alt=media&token=cde6bf7e-c7bf-4b8e-a73f-560b62638d51<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FMerak3.png?alt=media&token=9f82f14d-dd46-4c68-9721-a5f4ccc3dae7<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FMerak4.png?alt=media&token=5a19a8b4-3202-4e9f-9983-68a89b8e8ce6",
			Latitude:        -7.7956,
			Longitude:       110.3695,
			StatusID:        4,
			HabitatID:       7,
			SpeciesID:       1,
		},
		{
			Name:            "Raflesia Arnoldi",
			LatinName:       "Rafflesia arnoldii",
			Populasi:        "300 - 400 Bunga",
			BeratBadan:      "7 - 11",
			UkuranTubuh:     "1 - 2",
			RentangUsia:     "1 - 2",
			Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fbanner%2FRaflesiaBanner.png?alt=media&token=9cd11f0c-d168-4658-a73d-93144c8a052f",
			Description:     "Hai sobat Flonn! Pernah dengar tentang Rafflesia arnoldi? Ini adalah salah satu bunga paling unik dan spektakuler di dunia. Kenapa? Karena Rafflesia arnoldi dikenal sebagai pemegang rekor bunga terbesar di planet ini, dengan diameter bisa mencapai hingga satu meter! Bunga ini juga terkenal dengan bau busuknya yang mirip dengan daging membusuk, yang berfungsi untuk menarik serangga seperti lalat yang berperan dalam proses penyerbukannya. Warna merah menyala dan bintik-bintik putih pada kelopaknya menambah keindahan yang kontras dengan aroma yang dikeluarkannya.<>Bunga ini memiliki siklus hidup yang cukup unik, sobat Flonn. Rafflesia arnoldi tidak memiliki daun, batang, atau akar yang nyata. Sebaliknya, mereka hidup sebagai parasit pada tanaman inang, biasanya pada anggota genus Tetrastigma, yang merupakan jenis anggur yang ditemukan di hutan tropis. Bunga ini menghabiskan sebagian besar hidupnya sebagai organisme tidak terlihat di dalam jaringan tanaman inangnya, hanya muncul ketika siap untuk mekar, yang hanya terjadi selama beberapa hari sebelum layu dan mati.<>Ditemukan di hutan-hutan tropis Indonesia, khususnya di Sumatera, Rafflesia arnoldi adalah ikon kebanggaan nasional dan sering menjadi subjek penelitian dan kekaguman. Namun, keindahan ini tidak mudah ditemukan, sobat Flonn. Mekarnya bunga ini adalah peristiwa langka dan sering kali membutuhkan timing yang tepat dan kondisi yang sesuai di hutan tempat mereka hidup. Para peneliti dan pecinta alam sering melakukan ekspedisi khusus hanya untuk menyaksikan mekarnya bunga ini.",
			Characteristics: "Ukuran dan Berat:Salah satu bunga terbesar di dunia, dengan diameter yang bisa mencapai lebih dari satu meter dan berat hingga 11 kilogram.<>Tanpa Batang, Daun, atau Akar Nyata:Tumbuh sebagai parasit dengan jaringan serat di dalam tanaman inang, khususnya tumbuhan anggur dari genus Tetrastigma.<>Bau Busuk:Mengeluarkan aroma khas seperti daging membusuk yang berfungsi untuk menarik serangga.<>Bentuk dan Warna Unik:Kelopak tebal dan berdaging dengan warna merah tua yang mencolok serta bintik-bintik putih krem di seluruh permukaannya.<>Periode Mekar yang Singkat:Hanya mekar beberapa hari sebelum mulai membusuk dan mati.<>Reproduksi yang Unik:Bergantung pada serangga untuk penyerbukan, yang tertarik pada bau bunga dan membantu membawa serbuk sari ke bunga lainnya.",
			Status:          "Terancam Punah (Endangered)<>Status konservasi ini diberikan oleh International Union for Conservation of Nature (IUCN) untuk spesies yang berada pada tingkat risiko kepunahan tertinggi, hanya satu langkah sebelum status punah di alam liar. Untuk Harimau Sumatera (Panthera tigris sumatrae), status ini menandakan bahwa populasinya telah mencapai angka yang sangat rendah dan kemungkinan untuk bertahan hidup semakin menipis akibat berbagai ancaman serius yang belum terselesaikan.<>Deforestasi untuk pertanian dan pembangunan merusak habitat Rafflesia.:Hanya bisa hidup parasit pada tumbuhan Tetrastigma tertentu.:Meskipun sulit dipindahkan atau disimpan lama, Rafflesia arnoldii tetap dicabut dari habitatnya untuk memenuhi permintaan kolektor tanaman langka.",
			CharacteristicsPhoto: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fcharacteristics%2FRaflesiaChar.png?alt=media&token=196b2959-5c39-4666-a9f5-001f67ac8009",
			StatusPhotos: "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FRaflesia1.png?alt=media&token=9055a8b9-7bac-4a5a-8826-c9c30705bb86<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FRaflesia2.png?alt=media&token=437a1a01-c622-49d6-9210-8a71c4414fc7<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FRaflesia3.png?alt=media&token=5603c22d-0a5a-4957-9cc7-983137f2952d<>https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2Fstatus%2FRaflesia4.png?alt=media&token=f4866fb7-e9a8-4687-b14c-fdfdadabde86",
			Latitude:        -0.9492,
			Longitude:       100.3543,
			StatusID:        5,
			HabitatID:       7,
			SpeciesID:       1,
		},
		// {
		// 	Name:            "Edelweiss Jawa",
		// 	LatinName:       "Anaphalis javanica",
		// 	Populasi:        "15000 per Hektar",
		// 	BeratBadan:      "0.1 - 0.5",
		// 	UkuranTubuh:     "0.1 - 0.7",
		// 	RentangUsia:     "1 - 2",
		// 	Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2FEDELWEIS%20JAWA.jpg?alt=media&token=2e32a6d5-fec1-42ec-8131-7c5d49251523",
		// 	Description:     "Hai, sobat Flonn! Sudah tahu belum tentang Edelweiss Jawa? Ini adalah salah satu bunga paling unik dan spektakuler di dunia. Kenapa? Karena Rafflesia arnoldi dikenal sebagai pemegang rekor bunga terbesar di planet ini, dengan diameter bisa mencapai hingga satu meter! Bunga ini juga terkenal dengan bau busuknya yang mirip dengan daging membusuk, yang berfungsi untuk menarik serangga seperti lalat yang berperan dalam proses penyerbukannya. Warna merah menyala dan bintik-bintik putih pada kelopaknya menambah keindahan yang kontras dengan aroma yang dikeluarkannya.<>Bunga ini memiliki siklus hidup yang cukup unik, sobat Flonn. Rafflesia arnoldi tidak memiliki daun, batang, atau akar yang nyata. Sebaliknya, mereka hidup sebagai parasit pada tanaman inang, biasanya pada anggota genus Tetrastigma, yang merupakan jenis anggur yang ditemukan di hutan tropis. Bunga ini menghabiskan sebagian besar hidupnya sebagai organisme tidak terlihat di dalam jaringan tanaman inangnya, hanya muncul ketika siap untuk mekar, yang hanya terjadi selama beberapa hari sebelum layu dan mati.<>Ditemukan di hutan-hutan tropis Indonesia, khususnya di Sumatera, Rafflesia arnoldi adalah ikon kebanggaan nasional dan sering menjadi subjek penelitian dan kekaguman. Namun, keindahan ini tidak mudah ditemukan, sobat Flonn. Mekarnya bunga ini adalah peristiwa langka dan sering kali membutuhkan timing yang tepat dan kondisi yang sesuai di hutan tempat mereka hidup. Para peneliti dan pecinta alam sering melakukan ekspedisi khusus hanya untuk menyaksikan mekarnya bunga ini.S",
		// 	Characteristics: "",
		// 	Status:          "",
		// 	Latitude:        -7.7956,
		// 	Longitude:       110.3695,
		// 	StatusID:        3,
		// 	HabitatID:       7,
		// 	SpeciesID:       1,
		// },
		// {
		// 	Name:            "Anggrek Hitam",
		// 	LatinName:       "Coelogyne pandurata",
		// 	Populasi:        "20000 Bunga",
		// 	BeratBadan:      "0.1 - 0.7",
		// 	UkuranTubuh:     "0.1 - 0.2",
		// 	RentangUsia:     "1 - 2",
		// 	Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2FPORTAL%20ANGGREK%20HITAM.jpeg?alt=media&token=91a29be2-8c26-4506-9bb6-cd5c6b90fbdb",
		// 	Description:     "Sobat Flonn, pernahkah kamu mendengar tentang anggrek hitam yang misterius? Anggrek hitam, atau yang dikenal dengan nama ilmiah Coelogyne pandurata, adalah salah satu spesies anggrek yang sangat unik dan jarang ditemukan. Keunikan ini bukan hanya karena warnanya yang gelap, tetapi juga karena corak dan bentuknya yang elegan. Bunga ini memiliki labellum (bibir bunga) berwarna hijau kehitaman dengan garis tengah yang menonjol berwarna hijau cerah, menciptakan kontras yang memikat mata.<>Berasal dari pulau Kalimantan, Indonesia, anggrek hitam tumbuh di lingkungan yang lembap dan teduh. Spesies ini umumnya ditemukan di hutan-hutan dataran rendah hingga dataran tinggi yang teduh. Anggrek ini memilih habitat di batang pohon atau di antara bebatuan, yang menjadikannya epifit yang baik. Keindahan alaminya di habitat asli memberikan pandangan yang sangat menarik bagi para penggemar anggrek dan penjelajah alam.<>Selain keindahannya, anggrek hitam juga memiliki nilai simbolis dan dipercaya sebagai simbol keberanian dan ketahanan. Tidak heran jika anggrek ini menjadi sangat populer di kalangan kolektor tanaman dan pecinta bunga. Kehadiran bunga ini dalam koleksi dapat menambah keanekaragaman dan keunikan, sekaligus memberi kesempatan untuk belajar lebih dalam tentang kekayaan flora Indonesia. Jadi, jika kamu tertarik untuk menambahkan sesuatu yang benar-benar istimewa ke dalam tamanmu, anggrek hitam bisa menjadi pilihan yang tepat.",
		// 	Characteristics: "",
		// 	Status:          "",
		// 	Latitude:        -2.2083,
		// 	Longitude:       113.9108,
		// 	StatusID:        3,
		// 	HabitatID:       7,
		// 	SpeciesID:       1,
		// },
		// {
		// 	Name:            "Cemara Gunung",
		// 	LatinName:       "Abies nebrodensis",
		// 	Populasi:        "18000 Pohon",
		// 	BeratBadan:      "200 - 300",
		// 	UkuranTubuh:     "25 - 30",
		// 	RentangUsia:     "15 - 30",
		// 	Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2FCemara%20gunung.jpg?alt=media&token=d986e871-5c42-4559-94c6-0e44428afdef",
		// 	Description:     "Hey, Sobat Flonn! Mari kita bahas cemara gunung. Pohon ini merupakan salah satu jenis pohon konifer yang kerap kita jumpai meramaikan kontur pegunungan tinggi. Cemara gunung, menancapkan akar di lereng-lereng dan puncak yang sering kali berkabut atau berangin. Mereka memiliki bentuk yang unik dengan daun yang ramping dan tajam, serta tumbuh mengelompok membentuk semacam payung yang padat.<>Salah satu keistimewaan cemara gunung adalah kemampuannya untuk bertahan hidup dalam kondisi tanah yang tidak subur. Pohon ini memiliki sistem akar yang kuat dan mampu menembus tanah batuan untuk mencari nutrisi. Hal ini menjadikan mereka pionir yang baik dalam proses reboisasi di area yang sulit ditumbuhi oleh jenis pohon lain. Mereka tidak hanya membantu stabilisasi tanah tapi juga memberikan habitat bagi banyak spesies hewan pegunungan.<>Tak hanya kekuatan fisik, cemara gunung juga menawarkan keindahan estetika yang dapat dinikmati siapa saja, Sobat Flonn. Baik itu hamparan cemara yang membentuk hutan konifer atau barisan pohon yang berdiri tegak menghiasi lanskap pegunungan, setiap pemandangan tersebut memberikan ketenangan dan inspirasi bagi para pendaki atau siapa saja yang mengagumi keindahan alam. Jadi, jika kamu berkesempatan mendaki gunung, jangan lupa untuk menghargai kehadiran cemara gunung yang telah lama menjadi penjaga alam di ketinggian tersebut!",
		// 	Characteristics: "",
		// 	Status:          "",
		// 	Latitude:        -8.5064,
		// 	Longitude:       115.2624,
		// 	StatusID:        3,
		// 	HabitatID:       7,
		// 	SpeciesID:       1,
		// },
		// {
		// 	Name:            "Lady's Slipper",
		// 	LatinName:       "Cypripedium calceolus",
		// 	Populasi:        "300 - 500 Ekor",
		// 	BeratBadan:      "0.1 - 0.7",
		// 	UkuranTubuh:     "0.2 - 0.6",
		// 	RentangUsia:     "1 - 2",
		// 	Photo:           "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/biodiversity%2FLadys%20slipper.jpg?alt=media&token=b2e1df8c-119f-41fe-8095-4ae6e5b8f364",
		// 	Description:     "Sobat Flonn, pernahkah kamu mendengar tentang Lady's Slipper? Ini bukan sembarang sepatu, tapi sejenis anggrek yang sangat unik dan menarik. Lady's Slipper, atau anggrek sepatu wanita, mendapat namanya dari bentuk labellumnya yang menyerupai sepatu. Tumbuhan ini termasuk dalam genus Paphiopedilum, Cypripedium, Phragmipedium, dan Selenipedium, yang semuanya memamerkan keindahan yang memikat dalam dunia flora.<>Hal yang membuat Lady's Slipper begitu istimewa adalah bentuk bunganya yang eksentrik dan warna-warni yang cerah. Bunga ini memiliki 'sepatu' atau kantung yang berfungsi sebagai perangkap serangga, membantu dalam proses polinasi. Struktur ini tidak hanya unik tapi juga sangat efektif untuk memastikan kelangsungan hidup spesies dengan menarik perhatian serangga penyerbuk. Setiap bunga mampu bertahan selama berminggu-minggu, lebih lama dari kebanyakan anggrek lain, yang menjadikannya sangat populer di kalangan pengoleksi dan pecinta tanaman.<>Namun, sayangnya, banyak spesies Lady's Slipper yang sekarang terancam punah. Perusakan habitat dan perdagangan ilegal anggrek ini telah menyebabkan penurunan drastis dalam jumlahnya di alam liar. Beberapa spesies sudah masuk dalam daftar merah IUCN dan dilindungi oleh peraturan CITES yang melarang perdagangan internasional tanaman ini tanpa izin yang sesuai. Upaya konservasi kini sedang dilakukan untuk memastikan bahwa keindahan alami Lady's Slipper dapat dinikmati oleh generasi mendatang, Sobat Flonn.",
		// 	Characteristics: "",
		// 	Status:          "",
		// 	Latitude:        -5.50,
		// 	Longitude:       108.50,
		// 	StatusID:        4,
		// 	HabitatID:       7,
		// 	SpeciesID:       1,
		// },
	}

	if err := sql.Create(&objects).Error; err != nil {
		return err
	}
	return nil
}
