package seeds

import (
	"flonn-be/pkg/entity"
	"time"

	"gorm.io/gorm"
)

func (s *seeder) seedDummyDisaster(sql *gorm.DB) error {
	var objects []entity.Disaster

	if err := sql.First(&objects).Error; err != gorm.ErrRecordNotFound {
		return err
	}
	objects = []entity.Disaster{
		{
			DisasterTypeID: 1,
			Location:       "Denpasar",
			Province:       "Bali",
			Description:    "Gempa bumi terjadi di wilayah Denpasar",
			Date:           time.Date(2023, 1, 15, 12, 0, 0, 0, time.UTC),
			MonetaryLoss:   25000.75,
			BuildingDamage: 8,
			Deaths:         5,
			Injured:        15,
			Missing:        2,
			Evacuated:      30,
			Latitude:       -8.6500,
			Longitude:      115.2167,
		},
		{
			DisasterTypeID: 2,
			Location:       "Bandung",
			Province:       "Jawa Barat",
			Description:    "Banjir terjadi di wilayah Bandung",
			Date:           time.Date(2023, 2, 20, 15, 30, 0, 0, time.UTC),
			MonetaryLoss:   30000.25,
			BuildingDamage: 6,
			Deaths:         3,
			Injured:        12,
			Missing:        1,
			Evacuated:      25,
			Latitude:       -6.2088,
			Longitude:      106.8456,
		},
		{
			DisasterTypeID: 3,
			Location:       "Surabaya",
			Province:       "Jawa Timur",
			Description:    "Kebakaran hebat melanda Surabaya",
			Date:           time.Date(2023, 3, 10, 8, 0, 0, 0, time.UTC),
			MonetaryLoss:   15000.50,
			BuildingDamage: 4,
			Deaths:         1,
			Injured:        8,
			Missing:        0,
			Evacuated:      18,
			Latitude:       -7.2575,
			Longitude:      112.7521,
		},
		{
			DisasterTypeID: 4,
			Location:       "Medan",
			Province:       "Sumatera Utara",
			Description:    "Angin topan melanda Medan",
			Date:           time.Date(2023, 4, 5, 10, 45, 0, 0, time.UTC),
			MonetaryLoss:   20000.30,
			BuildingDamage: 7,
			Deaths:         4,
			Injured:        10,
			Missing:        2,
			Evacuated:      22,
			Latitude:       3.5952,
			Longitude:      98.6722,
		},
		{
			DisasterTypeID: 5,
			Location:       "Pontianak",
			Province:       "Kalimantan Barat",
			Description:    "Tsunami terjadi di wilayah Pontianak",
			Date:           time.Date(2023, 5, 18, 14, 20, 0, 0, time.UTC),
			MonetaryLoss:   18000.80,
			BuildingDamage: 5,
			Deaths:         3,
			Injured:        15,
			Missing:        1,
			Evacuated:      28,
			Latitude:       -0.0225,
			Longitude:      109.3425,
		},
		{
			DisasterTypeID: 6,
			Location:       "Makassar",
			Province:       "Sulawesi Selatan",
			Description:    "Longsor besar melanda Makassar",
			Date:           time.Date(2023, 6, 7, 18, 30, 0, 0, time.UTC),
			MonetaryLoss:   22000.40,
			BuildingDamage: 6,
			Deaths:         2,
			Injured:        12,
			Missing:        0,
			Evacuated:      20,
			Latitude:       -5.1477,
			Longitude:      119.4325,
		},
		{
			DisasterTypeID: 7,
			Location:       "Padang",
			Province:       "Sumatera Barat",
			Description:    "Gelombang pasang tinggi melanda Padang",
			Date:           time.Date(2023, 7, 23, 6, 45, 0, 0, time.UTC),
			MonetaryLoss:   17000.60,
			BuildingDamage: 5,
			Deaths:         1,
			Injured:        8,
			Missing:        0,
			Evacuated:      15,
			Latitude:       -0.9536,
			Longitude:      100.3510,
		},
		{
			DisasterTypeID: 8,
			Location:       "Manado",
			Province:       "Sulawesi Utara",
			Description:    "Gempa bumi dan tsunami terjadi di Manado",
			Date:           time.Date(2023, 8, 12, 22, 15, 0, 0, time.UTC),
			MonetaryLoss:   25000.75,
			BuildingDamage: 7,
			Deaths:         4,
			Injured:        10,
			Missing:        2,
			Evacuated:      22,
			Latitude:       1.4886,
			Longitude:      124.8457,
		},
		{
			DisasterTypeID: 1,
			Location:       "Semarang",
			Province:       "Jawa Tengah",
			Description:    "Kebakaran besar terjadi di wilayah Semarang",
			Date:           time.Date(2023, 9, 5, 14, 0, 0, 0, time.UTC),
			MonetaryLoss:   20000.30,
			BuildingDamage: 6,
			Deaths:         3,
			Injured:        12,
			Missing:        1,
			Evacuated:      25,
			Latitude:       -6.9667,
			Longitude:      110.4167,
		},
		{
			DisasterTypeID: 2,
			Location:       "Palembang",
			Province:       "Sumatera Selatan",
			Description:    "Banjir bandang melanda Palembang",
			Date:           time.Date(2023, 10, 20, 9, 30, 0, 0, time.UTC),
			MonetaryLoss:   18000.80,
			BuildingDamage: 5,
			Deaths:         2,
			Injured:        15,
			Missing:        1,
			Evacuated:      30,
			Latitude:       -2.9761,
			Longitude:      104.7754,
		},
		{
			DisasterTypeID: 4,
			Location:       "Bululawang",
			Province:       "Jawa Timur",
			Description:    "Bencana tambahan di Kecamatan Bululawang, Malang",
			Date:           time.Now(),
			MonetaryLoss:   7500.0,
			BuildingDamage: 3,
			Deaths:         2,
			Injured:        5,
			Missing:        0,
			Evacuated:      10,
			Latitude:       -8.0775,
			Longitude:      112.6374,
		},
	}

	if err := sql.Create(&objects).Error; err != nil {
		return err
	}
	return nil
}
