package seeds

import (
	"flonn-be/pkg/entity"

	"gorm.io/gorm"
)

func (s *seeder) seedDummyOpenCampaign(sql *gorm.DB) error {
	var objects []entity.OpenCampaign

	if err := sql.First(&objects).Error; err != gorm.ErrRecordNotFound {
		return err
	}
	objects = []entity.OpenCampaign{
		{
			Title:       "Say No to Plastic",
			IsPositive:  false,
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/campaign%2FBANNER%20SAY%20NO%20TO%20PLASTIC.jpg?alt=media&token=e4d7c3d0-7ed3-44b4-a0ba-113dbf33d38a",
			Highlight:   `"Say No to Plastic" bukan sekadar slogan, melainkan gerakan kita bersama untuk kehidupan yang lebih hijau. Lewat inisiatif ini, kita mengajak Sobat Flonn untuk beraksi mulai dari yang paling sederhana seperti gunakan tas belanja ulang pakai dan bawa botol minum pribadi. Klik "Mulai Beraksi" dan ambil langkah cerdas untuk lingkungan, mulai hari ini!.`,
			Description: `Tentang “say no to plastic”##Dalam menghadapi tantangan lingkungan yang semakin mendesak, kampanye "Say No to Plastic" bertujuan untuk mengurangi penggunaan plastik sekali pakai yang telah lama memberikan dampak negatif terhadap alam. Mulailah dengan langkah sederhana seperti menggunakan tas belanja yang dapat digunakan kembali dan membawa botol minum pribadi. Langkah-langkah kecil ini, ketika dilakukan secara konsisten, dapat membawa perubahan besar terhadap kelestarian lingkungan kita. Dengan berpartisipasi dalam kampanye "Say No to Plastic," Sobat Flonn tidak hanya membantu mengurangi sampah plastik, tapi juga menjadi bagian dari gerakan global untuk kehidupan yang lebih hijau.`,
			Keterangan:  "apa dampak negatif dari plastik sekali pakai?##Plastik sekali pakai sangat sulit terurai dan bisa bertahan di alam selama ratusan tahun, mengakibatkan polusi yang masif di lingkungan. Di lautan, plastik sekali pakai seperti tas belanja, sedotan, dan bungkus makanan berakhir mengotori perairan dan membahayakan kehidupan laut. Tidak hanya menumpuk sebagai sampah, plastik juga dapat memecah menjadi partikel mikro yang lebih kecil, yang kemudian dikonsumsi oleh hewan laut. Partikel ini berpotensi mengkontaminasi rantai makanan, bahkan bisa berakhir di piring makan kita, membawa dampak negatif terhadap kesehatan manusia.<>Selain itu, produksi plastik sekali pakai menghabiskan sumber daya alam yang berharga dan menghasilkan emisi karbon yang tinggi. Proses produksinya seringkali melibatkan penggunaan bahan kimia berbahaya yang dapat mencemari udara, air, dan tanah. Ini tidak hanya merusak habitat alami tetapi juga mempengaruhi kesehatan komunitas yang tinggal di dekat fasilitas produksi plastik. Dengan menurunkan ketergantungan kita pada plastik sekali pakai, kita tidak hanya mengurangi dampak langsung terhadap lingkungan tetapi juga mendukung prinsip ekonomi sirkular yang lebih berkelanjutan.",
			Steps:       "Bawa tas belanja sendiri ketika berbelanja.<>Gunakan botol minum dan wadah makanan yang dapat digunakan.<>Belanja di toko yang menawarkan barang tanpa kemasan, atau pilih produk dengan kemasan yang bisa didaur ulang atau biodegradable.<>Bawa peralatan makan sendiri seperti garpu, sendok, dan sedotan yang bisa dicuci dan digunakan kembali.<>Hindari pembelian makanan cepat saji yang sering kali dikemas dalam plastik dan styrofoam.<>Pisahkan sampah plastik dari jenis sampah lainnya dan pastikan sampah plastik tersebut masuk ke fasilitas daur ulang yang tepat.<>Edukasi keluarga dan teman tentang pentingnya mengurangi penggunaan plastik dan bagaimana mereka juga bisa berkontribusi.",
		},
		{
			Title:       "RECYCLE FOR LIFE",
			IsPositive:  true,
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/campaign%2FBANNER%20RECYCLE%20FOR%20LIFE.jpg?alt=media&token=cdc7fbbb-5010-4299-ab84-3038213d2fd2",
			Highlight:   `Di "Recycle for Life", dengan hanya memilah sampah dan mendaur ulang barang-barang yang tidak terpakai, Sobat Flonn telah membantu mengurangi limbah dan menghemat sumber daya alam. Klik 'Mulai Beraksi' sekarang dan jadilah pahlawan bagi planet kita dengan tindakan sederhana yang berdampak besar. Bersama-sama, kita bisa membuat perubahan yang berarti untuk bumi yang kita cintai!`,
			Description: `CINTAI LINGKUNGAN DENGAN “HIDUPKAN HARIMU”##Halo, Sobat Flonn! Mari bergabung dengan kami dalam misi 'Hijaukan Harimu' dan berikan sentuhan hijau pada setiap sudut ruanganmu. Setiap tanaman yang kamu tanam bukan hanya sekedar dekorasi, tetapi juga langkah kecil kita bersama menuju revitalisasi Bumi ini. Di Flonn, kami yakin bahwa tindakan kecil seperti menambahkan pot tanaman dapat memulai perubahan besar terhadap lingkungan kita. Dengan memilih untuk hijau, kamu tak hanya berkontribusi pada masa depan yang lebih berkelanjutan, tapi juga mendukung upaya kita dalam meningkatkan kualitas udara yang kita hirup. Ayo, bersama-sama kita tanam lebih banyak harapan, dan rasakan udara segar yang kita ciptakan bersama. Gabung sekarang dan mulai lihat perubahan nyata yang bisa Sobat Flonn buat, satu tanaman pada satu waktu.`,
			Keterangan:  "rasakan manfaat menakjubkan dari menghijaukan lingkunganmu##Mulai dari udara yang lebih bersih berkat tanaman yang menyaring polutan dan memproduksi oksigen, hingga pengurangan jejak karbon yang mendukung perang melawan perubahan iklim. Menanam tanaman tidak hanya menguntungkan Bumi, tapi juga membantu mengelola air hujan dan mengurangi erosi. Plus, kamu bisa merasakan peningkatan kesehatan dan kesejahteraan emosional, sebab berkebun terbukti efektif mengurangi stres dan meningkatkan mood.<>Selain itu, 'Hidupkan Harimu' juga mengajak kamu untuk membangun komunitas yang kuat sambil belajar banyak hal tentang keberlanjutan. Menikmati estetika ruang hijau yang lebih indah dan menanam tanamanmu sendiri, seperti sayuran dan herbal, tidak hanya menghemat uang tetapi juga bisa meningkatkan nilai properti. Jadi, tidak hanya mendapatkan lingkungan yang lebih hijau dan sehat, kamu juga belajar keterampilan berkebun yang berguna dan meningkatkan kesadaran akan pentingnya menjaga alam. Ayo, manfaatkan kesempatan ini untuk melakukan perubahan positif, satu tanaman pada satu waktu!",
			Steps:       "Pilih beberapa jenis tanaman yang mudah dirawat untuk memulai, seperti sukulen, lidah mertua, atau philodendron.<>Manfaatkan jendela, balkon, atau sudut ruangan yang belum terpakai untuk meletakkan pot tanaman.<>Gunakan air bekas yang masih layak pakai untuk menyiram tanaman atau kumpulkan air hujan sebagai alternatif.<>Gunakan barang-barang bekas seperti kaleng, botol plastik, atau potongan pipa sebagai pot tanaman. Ini tidak hanya mengurangi sampah, tapi juga menambah nilai estetika yang unik.<>Pelajari cara membuat kompos dari sisa makanan. Kompos dapat digunakan untuk menyuburkan tanah, meningkatkan pertumbuhan tanaman, dan mengurangi limbah rumah tangga.<>Tetapkan jadwal reguler untuk menyiram dan memupuk tanaman kamu, memastikan bahwa mereka mendapatkan perawatan yang mereka butuhkan untuk tumbuh sehat.<>Ajak teman atau keluarga untuk memulai berkebun. Berbagi pengetahuan dan pengalaman dapat memotivasi lebih banyak orang untuk mulai berkebun.",
		},
		{
			Title:       "Hijaukan Harimu",
			IsPositive:  true,
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/campaign%2Fmarkus-spiske-4PG6wLlVag4-unsplash.jpg?alt=media&token=1d499331-dc60-4729-a766-14054a6efcbb",
			Highlight:   `Gabung dalam gerakan "Hijaukan Harimu" dan jadilah bagian dari revolusi hijau. Dengan setiap tindakan kecil, kita dapat membuat perubahan besar. Mari tanam lebih banyak kehidupan, satu pot tanaman dalam waktu bersamaan. Bersama, kita dapat mendorong gaya hidup yang lebih berkelanjutan dan menyegarkan udara yang kita hirup.`,
			Description: `Ubah Sampah Menjadi berharga melalui “Recycle of life”##Kenalan sama kampanye 'Recycle for Life' yuk! Sebuah gerakan di mana Sobat Flonn bisa bertransformasi menjadi pahlawan lingkungan sehari-hari. Setiap botol, kertas, atau benda tak terpakai yang kamu daur ulang bukan hanya mengurangi limbah yang menumpuk di tempat pembuangan akhir, tapi juga menghemat sumber daya alam yang berharga. Di Flonn, kami percaya bahwa setiap tindakan kecil memiliki kekuatan untuk menciptakan gelombang perubahan yang besar. Dengan mengklik 'Mulai Beraksi', kamu tidak hanya memulai perjalanan daur ulangmu, tapi juga membantu menyebarkan kesadaran tentang pentingnya daur ulang dalam memelihara bumi kita. Mari kita ciptakan masa depan yang lebih berkelanjutan dengan bergabung bersama di 'Recycle for Life'.`,
			Keterangan:  "APA MANFAAT DARI MENDAUR ULANG SAMPAH?##Dengan hanya mendaur ulang, Sobat Flonn bisa membantu mengurangi jumlah sampah yang menumpuk di tempat pembuangan akhir. Bayangkan saja, setiap barang yang kita daur ulang menghemat sumber daya alam, mengurangi kebutuhan untuk memproses bahan baku baru, dan memotong jumlah emisi berbahaya yang dilepaskan ke atmosfer. Ini bukan hanya soal menjaga bumi tetap hijau, tapi juga tentang membuat pilihan cerdas yang mendukung efisiensi ekonomi, membuka lapangan kerja baru, dan menambah nilai ekonomi barang yang kita anggap 'sampah'.<>Dan bukan hanya lingkungan yang diuntungkan, Sobat Flonn juga bisa merasakan dampak positifnya! Dari meningkatkan kesadaran lingkungan di kalangan komunitas, memacu inovasi dalam teknologi daur ulang, hingga membantu menciptakan lingkungan yang lebih bersih dan sehat untuk kita semua. Daur ulang mengajarkan kita dan generasi mendatang tentang pentingnya menjaga bumi dan menunjukkan bahwa setiap tindakan, tidak peduli seberapa kecil, adalah langkah penting dalam membangun masa depan yang lebih berkelanjutan. Ayo, mulai dari sekarang, lakukan bagianmu dan rasakan manfaatnya!",
			Steps:       "Mulailah dengan memisahkan sampah organik dan non-organik. Gunakan tempat sampah berbeda untuk kertas, plastik, logam, dan kaca.<>Kenali simbol daur ulang pada kemasan produk untuk memastikan bahwa Anda membuang sampah ke tempat yang tepat.<>Sebelum membuang barang, pertimbangkan apakah ada cara untuk menggunakan ulang atau mengubahnya menjadi sesuatu yang baru, seperti mengubah kaleng bekas menjadi pot tanaman.<>Barang yang tidak lagi digunakan namun masih dalam kondisi baik bisa didonasikan ke panti asuhan atau organisasi amal.<>Mendukung bisnis yang menggunakan bahan daur ulang dalam produk mereka atau yang mempraktikkan keberlanjutan dalam operasional mereka.<>Jadilah lebih sadar tentang penggunaan barang-barang yang Anda beli dan cari cara untuk memperpanjang umur pakainya sebelum memutuskan untuk membuangnya.<>Bagikan pengetahuan dan praktek daur ulang Anda dengan teman dan keluarga. Menjadi contoh yang baik bisa memotivasi orang lain untuk mulai daur ulang.",
		},
	}

	if err := sql.Create(&objects).Error; err != nil {
		return err
	}
	return nil
}
