package seeds

import (
	"flonn-be/pkg/entity"
	"time"

	"gorm.io/gorm"
)

func (s *seeder) seedDummyOpenVolunteer(sql *gorm.DB) error {
	var objects []entity.OpenVolunteer

	if err := sql.First(&objects).Error; err != gorm.ErrRecordNotFound {
		return err
	}

	parseTime := func(str string) time.Time {
		startDate, _ := time.Parse("2006-01-02", str)
		return startDate
	}

	objects = []entity.OpenVolunteer{
		{
			Title:       "Relawan Konservasi Penyu",
			Subtitle:    "Penyelamat alam",
			Location:    "Pantai Kuta, Bali",
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/volunteer%2FBannerPenyu.png?alt=media&token=0c5c4643-e85a-4499-abde-2d48d1fcdd47",
			Description: "FLONN mengajak para Flonteer untuk terjun langsung dalam aksi konservasi penyu di Pantai Kuta, Bali. Bergabung menjadi Flonteer dan mengambil bagian dalam kegiatan mulai dari pemantauan habitat hingga penyelamatan penyu yang terluka. Di sini, setiap tindakan Flonteer berkontribusi pada pelestarian kehidupan laut. Kegiatan edukasi yang dilakukan juga membuka mata masyarakat tentang pentingnya menjaga keberlangsungan spesies ini. Jadi, siapkah Sobat Flonn untuk membuat perbedaan? Gabung sekarang dan bantu FLONN menjaga agar pantai ini tetap menjadi rumah yang aman bagi penyu untuk generasi yang akan datang.",
			StartDate:   parseTime("2024-06-23"),
			EndDate:     parseTime("2024-08-11"),
			Tasks:       "Pemantauan Habitat:Flonteer akan melakukan pemantauan rutin di pantai untuk menilai kondisi habitat penyu, mencakup pemantauan kualitas air, kondisi pasir, dan area bertelur. Tugas ini penting untuk memastikan bahwa habitat tersebut tetap kondusif untuk kegiatan bertelur penyu.<>Penyelamatan Penyu yang Terluka:Jika menemukan penyu yang terluka atau dalam kondisi yang tidak baik, Flonteer akan terlibat dalam proses penyelamatan. Ini termasuk pertolongan pertama di lokasi dan mengkoordinasikan dengan fasilitas rehabilitasi lokal untuk perawatan lebih lanjut.<>Penetasan Telur dan Pelepasan Tukik:Flonteer akan membantu dalam proses penetasan telur penyu. Mereka akan mengawasi dan melindungi telur hingga menetas dan kemudian membantu dalam pelepasan tukik ke laut, memastikan mereka memiliki kesempatan terbaik untuk bertahan hidup.<>Edukasi Komunitas:Flonteer akan terlibat dalam program edukasi untuk masyarakat lokal dan pengunjung pantai. Kegiatan ini bertujuan untuk meningkatkan kesadaran tentang pentingnya pelestarian penyu dan cara-cara yang dapat dilakukan masyarakat untuk mendukung usaha ini.<>Pengumpulan Data untuk Penelitian:Selama kegiatan di lapangan, Flonteer akan mengumpulkan data yang penting untuk penelitian konservasi penyu seperti pengamatan perilaku penyu, pencatatan jumlah telur yang diletakkan, dan monitoring populasi.<>Pembersihan Pantai:Flonteer akan terlibat dalam kegiatan rutin pembersihan pantai untuk mengurangi polusi dan memastikan pantai tetap bersih dan aman bagi penyu yang bertelur",
			Condition:   "WNI (Warga Negara Indonesia)<>20-45 tahun<>Pengalaman bekerja dalam proyek konservasi lingkungan, terutama yang berhubungan dengan kehidupan laut atau spesies terancam punah, memberi pemahaman yang lebih baik tentang tantangan dan solusi praktis dalam pelestarian.:Pengalaman dalam melakukan pekerjaan lapangan, seperti pengambilan sampel, pemantauan spesies, atau aktivitas serupa di alam bebas.:Pengalaman berbicara di depan publik, yang berguna dalam menyampaikan pesan konservasi kepada audiens yang lebih luas atau dalam acara edukasi.<>Tidak ada batasan khusus mengenai jenjang pendidikan, namun latar belakang di bidang biologi, lingkungan, kelautan, atau pendidikan terkait lainnya akan menjadi nilai tambah.<>Bahasa Indonesia dan Bahasa Inggris<>Mampu berkomunikasi dengan baik dalam Bahasa Indonesia dan/atau Bahasa Inggris.:Mampu berinteraksi dengan berbagai kelompok, termasuk tim internal, masyarakat lokal, dan turis, dalam menyampaikan informasi atau mengatur aktivitas.:Memiliki kemampuan observasi yang baik, terutama dalam mengamati perilaku hewan atau kondisi alam.:Cukup fit untuk melakukan kegiatan di luar ruangan seperti berjalan di pantai, mengangkat atau membawa peralatan.:Mampu mengelola waktu dan sumber daya secara efisien untuk memenuhi kebutuhan program dan jadwal kegiatan.:Kemampuan untuk mengidentifikasi dan menangani masalah yang muncul selama aktivitas konservasi.",
		},
		{
			Title:       "PAHLAWAN PEMULIHAN",
			Subtitle:    "Relawan Bencana Banjir di Kalimantan Selatan",
			Location:    "Kecamatan Batu Benawa, Kabupaten Hulu Sungai, Kalimantan Selatan",
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/volunteer%2FBannerKalimantan.png?alt=media&token=7af61661-eea7-40b9-bbbb-e7287b5f8c5b",
			Description: "FLONN mengajak para Flonteer untuk membantu masyarakat yang terdampak bencana banjir di Kecamatan Batu Benawa, Kalimantan Selatan. Bergabung menjadi Flonteer berarti berperan aktif dalam upaya penanganan pasca-banjir, mulai dari distribusi bantuan, pemulihan infrastruktur, hingga memberikan dukungan psikososial bagi warga yang terdampak. Setiap langkah yang diambil oleh Flonteer di lapangan akan membantu memulihkan kehidupan masyarakat setempat. Bersama FLONN, mari kita ciptakan perubahan nyata dan bantu mereka bangkit dari bencana.",
			StartDate:   parseTime("2024-04-20"),
			Tasks:       "Distribusi Bantuan:Flonteer akan membantu dalam distribusi logistik kepada warga yang terdampak bencana banjir, seperti makanan, air bersih, pakaian, dan perlengkapan kebersihan.<>Pemulihan Infrastruktur:Bekerja sama dengan tim teknis, Flonteer akan terlibat dalam membersihkan puing-puing dan memperbaiki fasilitas umum yang rusak seperti jembatan, jalan, dan sarana air bersih.<>Dukungan Psikososial:Flonteer akan memberikan dukungan emosional dan psikologis kepada para korban bencana, terutama kepada anak-anak dan keluarga yang mengalami trauma akibat banjir.<>Pengelolaan Posko Pengungsian:Terlibat dalam pengelolaan posko pengungsian, termasuk distribusi logistik di dalam posko, manajemen ruang, dan memastikan sanitasi serta keamanan di area pengungsian.<>Edukasi Kesehatan dan Kebersihan:Flonteer akan membantu mengedukasi warga tentang pentingnya menjaga kebersihan dan kesehatan selama masa pasca-banjir untuk mengurangi risiko penyakit yang sering muncul setelah bencana, seperti diare dan infeksi kulit.<>Pengumpulan Data dan Pemantauan:Flonteer juga akan membantu dalam pengumpulan data warga terdampak, kondisi rumah yang rusak, dan laporan terkait bantuan yang telah didistribusikan untuk memudahkan pelaporan ke lembaga terkait.",
			Condition:   "WNI (Warga Negara Indonesia)<>20-45 tahun<>Pengalaman bekerja dalam penanganan bencana alam atau situasi darurat lebih diutamakan, namun tidak wajib.:Pengalaman dalam kegiatan lapangan seperti distribusi logistik, pemulihan infrastruktur, atau bekerja dengan masyarakat di area terdampak.:Pengalaman dalam memberikan dukungan psikososial kepada komunitas atau korban bencana menjadi nilai tambah.<>Tidak ada batasan khusus mengenai jenjang pendidikan, namun latar belakang di bidang kebencanaan, kesehatan masyarakat, atau ilmu sosial terkait bisa menjadi nilai tambah.<>Bahasa Indonesia (kemampuan bahasa lokal Kalimantan Selatan adalah nilai tambah).<>Mampu bekerja dalam situasi darurat dengan cepat dan tanggap.:Mampu berkomunikasi dengan baik dalam Bahasa Indonesia dan bekerja dengan berbagai kelompok, termasuk masyarakat lokal dan tim relawan lainnya.:Memiliki ketahanan fisik yang baik untuk bekerja dalam kondisi lapangan yang sulit.:Mampu mengelola stres dan tetap tenang di bawah tekanan.:Mampu bekerja secara kolaboratif dalam tim serta memiliki kepedulian tinggi terhadap kondisi masyarakat terdampak bencana.:Berkomitmen untuk membantu masyarakat dan terbuka terhadap tugas yang fleksibel sesuai kebutuhan di lapangan.",
		},
		{
			Title:       "GARDA DEPAN BANTUAN",
			Subtitle:    "Relawan Erupsi Gunung Semeru",
			Location:    "Lereng Gunung Semeru, Kabupaten Lumajang, Jawa Timur",
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/volunteer%2FBannerSemeru.png?alt=media&token=4c875d90-ba6d-4c25-95e2-6fa5b306ee41",
			Description: "FLONN mengundang para Flonteer untuk bergabung dalam aksi penanggulangan bencana di wilayah terdampak erupsi Gunung Semeru. Flonteer akan terlibat dalam berbagai tugas mulai dari evakuasi warga, distribusi bantuan, hingga pemulihan infrastruktur dan memberikan dukungan psikososial bagi korban bencana. Bencana erupsi tidak hanya merusak infrastruktur, tetapi juga mempengaruhi kehidupan warga. Dengan menjadi Flonteer, kamu akan membantu memulihkan kehidupan masyarakat yang terdampak sekaligus membantu mengurangi dampak erupsi. Bersama FLONN, mari kita berikan harapan baru kepada mereka yang terdampak.",
			StartDate:   parseTime("2024-04-25"),
			EndDate:     parseTime("2024-06-20"),
			Tasks:       "Evakuasi Warga:Flonteer akan membantu proses evakuasi warga dari zona bahaya ke tempat yang lebih aman, bekerja sama dengan tim penyelamat dan aparat setempat.<>Distribusi Bantuan:Terlibat dalam distribusi logistik seperti makanan, air bersih, pakaian, dan peralatan medis kepada warga yang terdampak erupsi di tempat pengungsian.<>Penyediaan Dukungan Psikososial:Memberikan dukungan emosional kepada korban yang terdampak, terutama anak-anak dan orang lanjut usia yang mengalami trauma akibat erupsi.<>Pengelolaan Pengungsian:Flonteer akan membantu mengelola logistik, sanitasi, serta keamanan di posko pengungsian, memastikan area tersebut aman dan kondusif untuk pengungsi.<>Pemulihan Infrastruktur Sementara:Bersama tim teknis, Flonteer akan membantu dalam pembangunan fasilitas darurat, seperti tempat perlindungan sementara, pos kesehatan, dan dapur umum di area pengungsian.<>Pembersihan Area Terdampak:Flonteer akan terlibat dalam pembersihan area terdampak abu vulkanik dan material erupsi lain yang menghambat akses jalan atau mengancam keselamatan warga.<>Pengumpulan Data untuk Pemantauan:Membantu dalam pengumpulan data korban, kondisi rumah, serta kerugian yang dialami warga terdampak untuk dilaporkan ke lembaga terkait guna memfasilitasi bantuan yang tepat sasaran.",
			Condition:   "WNI (Warga Negara Indonesia)<>20-45 tahun<>Pengalaman bekerja di daerah bencana alam atau penanganan situasi darurat sangat dihargai, namun tidak wajib.:Pengalaman dalam distribusi logistik, pengelolaan pengungsian, atau pemulihan pasca-bencana menjadi nilai tambah.:Pengalaman memberikan dukungan psikososial atau bekerja dengan komunitas yang mengalami trauma menjadi keunggulan.<>Tidak ada batasan khusus mengenai pendidikan formal, tetapi latar belakang di bidang kebencanaan, kesehatan masyarakat, atau psikologi akan sangat membantu.<>Bahasa Indonesia (kemampuan bahasa lokal di daerah Jawa Timur adalah nilai tambah).<>Mampu berkomunikasi dengan baik dalam Bahasa Indonesia dan bekerja sama dengan berbagai kelompok, termasuk tim penyelamat, aparat, dan pengungsi.:Memiliki kemampuan bekerja di lingkungan yang penuh tekanan, khususnya di daerah terdampak bencana alam.:Fisik yang kuat dan siap bekerja dalam kondisi medan yang sulit, termasuk menghadapi abu vulkanik dan infrastruktur yang rusak.:Mampu bekerja dengan cepat dan tanggap dalam situasi darurat serta terbuka untuk penugasan yang fleksibel.:Memiliki kepedulian sosial yang tinggi terhadap masyarakat terdampak dan mampu menjaga ketenangan dalam situasi krisis.:Mampu mengelola waktu dan sumber daya secara efisien untuk mendukung kegiatan di lapangan, terutama dalam pemulihan pasca-erupsi.",
		},
		{
			Title:       "Konservator kehidupan",
			Subtitle:    "Relawan Pasca Kebakaran di Bukit Teletubies, Gunung Bromo",
			Location:    "Bukit Teletubies, Gunung Bromo, Jawa Timur",
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/volunteer%2FBannerBromo.png?alt=media&token=7b61a89e-d7b3-48ec-a94c-7837c5fd96c2",
			Description: "FLONN mengundang Flonteer untuk turut serta dalam upaya pemulihan pasca kebakaran di Bukit Teletubies, Gunung Bromo. Kebakaran hutan yang terjadi telah merusak ekosistem alami di kawasan ini, dan peran Flonteer sangat diperlukan untuk membantu pemulihan lingkungan, termasuk reboisasi, pengendalian erosi, dan pemulihan habitat alami satwa. Dengan terjun langsung ke lapangan, Flonteer akan membantu menjaga kelestarian salah satu kawasan wisata alam paling ikonik di Indonesia. Ayo bergabung, berikan kontribusimu dalam upaya menjaga alam dan melindungi keindahan Bukit Teletubies untuk generasi mendatang.",
			StartDate:   parseTime("2024-05-29"),
			EndDate:     parseTime("2024-06-29"),
			Tasks:       "Reboisasi dan Penanaman Kembali:Flonteer akan terlibat dalam program penanaman kembali tanaman-tanaman endemik yang hilang akibat kebakaran. Ini termasuk penanaman bibit pohon dan tanaman yang penting bagi ekosistem hutan di Bukit Teletubies.<>Pengendalian Erosi:Flonteer akan membantu memasang penghalang erosi di lereng-lereng bukit yang rawan, memastikan tanah tetap stabil dan tidak longsor pasca kebakaran.<>Pemulihan Habitat Satwa:Bekerja sama dengan tim konservasi, Flonteer akan membantu memperbaiki habitat alami untuk satwa liar di area yang terkena dampak, memastikan keberlanjutan ekosistem.<>Pembersihan Sisa Kebakaran:Flonteer akan terlibat dalam kegiatan pembersihan sisa-sisa kebakaran seperti ranting yang terbakar, batang pohon yang roboh, dan puing-puing lain yang mengganggu pemulihan area.<>Pengumpulan Data Ekologis:Flonteer akan membantu mengumpulkan data mengenai kondisi tanah, kerusakan vegetasi, serta dampak kebakaran terhadap ekosistem lokal. Data ini akan digunakan untuk perencanaan konservasi lebih lanjut.<>Edukasi Lingkungan kepada Masyarakat:Flonteer akan berpartisipasi dalam kegiatan edukasi dan penyuluhan kepada masyarakat lokal tentang pentingnya pencegahan kebakaran hutan, serta bagaimana mereka bisa berperan aktif dalam menjaga kelestarian lingkungan.",
			Condition:   "WNI (Warga Negara Indonesia)<>20-45 tahun<>Pengalaman di bidang konservasi lingkungan atau kegiatan lapangan terkait pemulihan hutan dan reboisasi sangat dihargai, tetapi tidak wajib.:Pengalaman bekerja di medan yang berat seperti area pegunungan atau hutan menjadi nilai tambah.:Pengalaman dalam memberikan edukasi lingkungan atau berinteraksi dengan masyarakat lokal adalah keunggulan.<>Tidak ada batasan khusus mengenai pendidikan formal, namun latar belakang dalam bidang biologi, kehutanan, atau ilmu lingkungan akan menjadi nilai tambah.<>Bahasa Indonesia (kemampuan bahasa lokal di daerah Jawa Timur adalah nilai tambah).<>Mampu bekerja di luar ruangan dan beradaptasi dengan medan yang bervariasi, seperti lereng bukit dan area terbuka.:Mampu bekerja dalam tim dengan baik dan berkomunikasi dengan berbagai kelompok, termasuk masyarakat lokal, tim konservasi, dan relawan lain.:Fisik yang cukup kuat untuk terlibat dalam kegiatan seperti penanaman kembali, pemasangan penghalang erosi, dan pembersihan area kebakaran.:Memiliki perhatian terhadap detail dalam pengumpulan data ekologis dan pemantauan kondisi lapangan.:Mampu bekerja dalam situasi yang penuh tekanan dan tetap tenang dalam menghadapi tantangan di lapangan.:Berkomitmen untuk menjaga kelestarian lingkungan dan terbuka terhadap tugas yang fleksibel sesuai dengan kondisi di lapangan.",
		},
		{
			Title:       "TIM TANGGAP DARURAT",
			Subtitle:    "Relawan Siap Siaga Gempa",
			Location:    "Kota Padang, Sumatera Barat",
			Photo:       "https://firebasestorage.googleapis.com/v0/b/flonn-pubek.appspot.com/o/volunteer%2FBannerGempa.png?alt=media&token=6f3478e1-e7dd-4488-a125-05fdcffcdf07",
			Description: "FLONN mengajak Flonteer untuk bergabung dalam program Relawan Siap Siaga Gempa di Kota Padang, Sumatera Barat, sebuah wilayah rawan gempa di Indonesia. Dalam program ini, Flonteer akan terlibat dalam kegiatan mitigasi bencana, termasuk membantu simulasi evakuasi gempa, penyuluhan kesiapsiagaan, serta pelatihan tanggap darurat bagi masyarakat lokal. Program ini dirancang untuk mempersiapkan komunitas agar lebih siap menghadapi potensi gempa di masa depan dan mengurangi risiko kerugian jiwa serta kerusakan infrastruktur. Bersama FLONN, mari kita membangun kesiapsiagaan bencana yang lebih kuat dan membantu menciptakan lingkungan yang lebih aman bagi semua.",
			StartDate:   parseTime("2024-05-17"),
			Tasks:       "Simulasi Evakuasi Gempa:Flonteer akan membantu dalam penyelenggaraan simulasi evakuasi darurat di sekolah-sekolah, perkantoran, dan area pemukiman. Tugas ini termasuk memberikan arahan mengenai jalur evakuasi aman, pengelolaan posko darurat, dan manajemen massa.<>Pelatihan Tanggap Darurat:Flonteer akan terlibat dalam pelatihan masyarakat tentang langkah-langkah tanggap darurat, seperti bagaimana bertindak cepat dan tepat saat gempa terjadi, penggunaan alat-alat keselamatan, serta cara berkomunikasi saat bencana.<>Penyuluhan Kesiapsiagaan:Melalui program edukasi, Flonteer akan menyampaikan informasi penting kepada warga mengenai tanda-tanda gempa, pentingnya persiapan seperti kit darurat, serta bagaimana memitigasi dampak gempa di rumah dan tempat kerja.<>Pengumpulan dan Distribusi Kit Darurat:Flonteer akan membantu mengumpulkan dan mendistribusikan kit darurat (berisi makanan, air, P3K, senter, dan peralatan komunikasi) kepada warga di area yang rawan gempa, untuk membantu kesiapan mereka dalam situasi darurat.<>Pemantauan Infrastruktur Publik:Bersama tim ahli, Flonteer akan membantu memeriksa kondisi infrastruktur di wilayah rawan gempa, seperti sekolah, rumah sakit, dan jembatan. Ini bertujuan untuk memastikan apakah bangunan tersebut siap menghadapi gempa atau memerlukan perbaikan.<>Edukasi Bahaya Pasca Gempa:Flonteer akan terlibat dalam memberikan edukasi tentang potensi bahaya pasca gempa, seperti tsunami atau gempa susulan, serta bagaimana merespons dengan tepat dalam situasi tersebut.",
			Condition:   "WNI (Warga Negara Indonesia)<>20-45 tahun<>Pengalaman dalam kegiatan tanggap darurat atau pelatihan bencana akan sangat dihargai, tetapi tidak wajib.:Pengalaman bekerja dalam kegiatan lapangan seperti simulasi evakuasi atau pengelolaan situasi darurat lebih diutamakan.:Pengalaman memberikan penyuluhan atau edukasi kepada masyarakat merupakan nilai tambah.<>Tidak ada batasan khusus mengenai pendidikan formal, tetapi latar belakang di bidang kebencanaan, keselamatan, atau pendidikan bencana akan sangat membantu.<>Bahasa Indonesia (kemampuan bahasa lokal di Sumatera Barat adalah nilai tambah).<>Mampu bekerja di bawah tekanan dan merespons dengan cepat dalam situasi darurat.:Mampu berkomunikasi dengan baik dalam Bahasa Indonesia dan berinteraksi dengan berbagai kelompok, termasuk masyarakat lokal dan tim penyelamat.:Memiliki fisik yang cukup kuat untuk bekerja di lingkungan yang tidak stabil pasca-gempa, termasuk berjalan di medan yang sulit.:Berpikir kritis dan mampu memberikan arahan dengan jelas kepada masyarakat dalam situasi krisis.:Mampu bekerja dalam tim, berkolaborasi dengan berbagai pihak seperti tim SAR, aparat setempat, dan organisasi kemanusiaan lainnya.:Memiliki pemahaman dasar tentang langkah-langkah kesiapsiagaan bencana dan alat-alat keselamatan dasar.",
		},
	}

	if err := sql.Create(&objects).Error; err != nil {
		return err
	}
	return nil
}
